version: "3.2"
services:
  snapdropnode:
    image: node:lts-alpine
    container_name: snapdropnode
    user: node
    working_dir: /home/node/app
    volumes:
      - ./server/:/home/node/app
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    command: ash -c "npm i && node index.js"
    restart: always